name: "$(SourceBranchName)+$(BuildID)"

# Prevents building every commit or on PR
trigger: none
pr: none

# Consume an artifact from the build pipeline as soon as it becomes available.
resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: summary-care-record
    source: "Summary-Care-Record-Build"
    trigger:
      branches:
        exclude:
          - 'master'
          - "refs/heads/master"
          - 'refs/tags/v*'

# env variables
variables:
  template: project.yml

  # AWS_ENV: ptl
  # FORCE_SANDBOX: false
  # NAMESPACE: from_branchname
  # PROXY_NAME: live

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    service_base_path: ${{ variables.service_base_path }}
    short_service_name: ${{ variables.short_service_name }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    deploy_review_sandbox: true
    # secret_ids:
    #   - ptl/cis/ldap.nis1.national.ncrs.nhs.uk/key
    #   - ptl/cis/ldap.nis1.national.ncrs.nhs.uk/crt
    #   - ptl/veit07.devspineservices.nhs.uk/root-ca/crt
    # config_ids:
    #   - /ptl/api-deployment/sds/ldap/private-key
    #   - /ptl/api-deployment/sds/ldap/client-cert
    #   - /ptl/api-deployment/sds/ldap/ca-certs
