name: "$(SourceBranchName)+$(BuildID)"

# Prevents building every commit or on PR
trigger: none
pr: none

# Consume an artifact from the build pipeline as soon as it becomes available.
resources:
  pipelines:
    - pipeline: summary-care-record
      source: "Summary-Care-Record-Build"
      trigger:
        branches:
          exclude:
            - 'master'
            - "refs/heads/master"
            - 'refs/tags/v*'
  repositories:
    - repository: templates
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital

# env variables
variables:
  SERVICE_NAME: summary-care-record
  SERVICE_BASE_PATH: summary-care-record
  PRODUCT_DISPLAY_NAME: Summary Care Record API
  PRODUCT_DESCRIPTION: This is a generated template API
  AWS_ENV: ptl
  FORCE_SANDBOX: false
  NAMESPACE: from_branchname
  PROXY_NAME: live

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DeployInternalDev
    displayName: internal-dev
    variables:
    - group: apigee-nonprod
    - group: env-internal-dev
    jobs:
      - deployment: DeployService
        displayName: Deploy Service
        environment: 'internal-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: az/templates/pre-tasks.yml@templates
                - template: az/templates/setup-build-name.yml@templates
                - template: az/templates/deploy-namespaced-service.yml@templates
