server:
  port: ${SCR_SERVER_PORT:9000}
  error:
    whitelabel:
        enabled: false

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
