server:
  port: ${SCR_SPINE_MOCK_SERVER_PORT:8081}
  
management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
