version: '3'

services:
  scr:
    image: uk.nhs/summary-care-record-api:0.0.1-SNAPSHOT
    ports:
        - "8080:8080"

  mock-spine-service:
    image: uk.nhs/spine-mock:0.0.1-SNAPSHOT
    ports:
        - "8081:8081"
