version: '3'

services:
  scr:
    image: local/summary-care-record-api:${BUILD_TAG}
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
  
  mock-spine-service:
    build:
      context: ./mock-spine-service
      dockerfile: Dockerfile
    ports:
        - "8081:8081"
