server:
  port: ${SCR_SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

spine:
  url: ${SCR_SPINE_URL:http://localhost:8081}
  acsEndpoint: /acs
  scrEndpoint: /summarycarerecord
  scrResultRepeatBackoff: 3000 # how much time to wait between Spine GET retries
  scrResultRepeatTimeout: 30000 # how much time to wait for all repeated Spine GET retries
  scrResultHardTimeout: 5000 # how much time to wait for a single Spine GET request
  scrResultTimeout: 30000 # how much time to wait for this SCR POST
  endpointCert: ""
  endpointPrivateKey: ""
  caCerts: ""