server:
  port: ${SCR_SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

scr:
  partyIdTo: ${SCR_PARTY_ID_TO:YEA-0000806}

spine:
  url: ${SCR_SPINE_URL:http://localhost:8081}
  acsEndpoint: /acs
  scrEndpoint: /clinical
  scrResultRepeatTimeout: 50000 # 50sec - how much time to wait for all repeated Spine GET retries
  scrResultTimeout: 60000 # 60sec - how much time to wait for this API entire SCR POST (Spine POST + polling Spine GET)
  endpointCert: ${SCR_SPINE_ENDPOINT_CERT:}
  endpointPrivateKey: ${SCR_SPINE_ENDPOINT_KEY:}
  caCerts: ${SCR_SPINE_ENDPOINT_CACERT:}