server:
  port: ${SCR_SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

spine:
  url: ${SCR_SPINE_URL:http://localhost:8081}
  acsEndpoint: /acs
  scrEndpoint: /summarycarerecord
  scrResultRepeatTimeout: 10000 # how much time to wait for all repeated Spine GET retries
  scrResultTimeout: 5000 # how much time to wait for this API entire SCR POST (Spine POST + polling Spine GET)
  endpointCert: ""
  endpointPrivateKey: ""
  caCerts: ""