server:
  port: ${SCR_SERVER_PORT:9000}
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

scr:
  partyIdFrom: ${SCR_PARTY_ID_FROM:TESTGEN-201324}
  partyIdTo: ${SCR_PARTY_ID_TO}
  nhsdAsidTo: ${SCR_NHSD_ASID_TO}

spine:
  url: ${SCR_SPINE_URL}
  acsEndpoint: /acs
  scrEndpoint: ${SCR_SPINE_ENDPOINT:/clinical}
  scrResultRepeatTimeout: ${SCR_SPINE_RESULT_REPEAT_TIMEOUT:50000} # 50sec - how much time to wait for all repeated Spine GET retries
  scrResultTimeout: ${SCR_SPINE_RESULT_TIMEOUT:60000} # 60sec - how much time to wait for this API entire SCR POST (Spine POST + polling Spine GET)
  endpointCert: ${SCR_SPINE_ENDPOINT_CERT:}
  endpointPrivateKey: ${SCR_SPINE_ENDPOINT_KEY:}
  caCerts: ${SCR_SPINE_ENDPOINT_CACERT:}
