server:
  port: ${SCR_SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

spine:
  url: ${SCR_SPINE_URL:http://localhost:8081}
  acsEndpoint: /acs
