spine:
    url: http://localhost:8081
    acsEndpoint: /acs

management:
    endpoints:
        web:
            base-path: /
            path-mapping.health: healthcheck
            exposure:
                include: info, health, metrics
