server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

scr:
  sandboxMode: ${SCR_SANDBOX_MODE:False}
  sandboxDelay: 200
  partyIdFrom: ${SCR_PARTY_ID_FROM:TESTGEN-201324}
  partyIdTo: ${SCR_PARTY_ID_TO:YEA-0000806}
  nhsdAsidTo: ${SCR_NHSD_ASID_TO:655159266510}
  serviceBasePath: ${SERVICE_BASE_PATH:summary-care-record/FHIR/R4}
  baseUrl: https://${HOST_URL:internal-dev.api.service.nhs.uk}

sds:
  baseUrl: https://${SDS_URL}

identity-service:
    userInfoEndpoint: /oauth2/userinfo
    baseUrl: https://${APIGEE_HOST:internal-dev.api.service.nhs.uk}

spine:
    useSsl: false
    url: ${SCR_SPINE_URL:http://localhost:8081}
    acsEndpoint: /sync-service
    alertEndpoint: /clinical/alert
    scrEndpoint: /clinical
    psisQueriesEndpoint: /sync-service
    scrResultRepeatTimeout: 4000
    scrResultTimeout: 5000
    connectionPool:
        maxTotalConnections: 10
        defaultKeepAliveTime: 20000
        connectionTimeout: 30000
        requestTimeout: 30000
        socketTimeout: 60000
        idleConnectionWaitTime: 30000
